name: Nintendo_CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_artifact:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run : mvn --file pom.xml -DskipTests clean install
      
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.jar'
  
  put_jar_in_container_and_push:
  
    runs-on: ubuntu-latest
    needs: [build_artifact]
    
    steps: 
    - uses: actions/checkout@v3
    
    - name: Docker login
      run : docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build the Docker image
      run : docker build . --file Dockerfile --tag dr1ff/nintendosdbot
      
    - name: Publish the Docker image
      run : docker push driff/nintendosdbot
    
    
    
    
    
    
