#--------------------------------------------------#
#       ______   ____      __   ______   ____      #
#      / ____/  /  _/    _/_/  / ____/  / __ \     #
#     / /       / /    _/_/   / /      / / / /     #
#    / /___   _/ /   _/_/    / /___   / /_/ /      #
#    \____/  /___/  /_/      \____/  /_____/       #
#                                                  #
#--------------------------------------------------#
name: Nintendo_CIx 

on:
  push:
    branches: [ "main" ]

jobs:

  build_docker_image_and_push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout        
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache       : maven  
        
    - name: Build with Maven
      run : mvn --file pom.xml -DskipTests clean install
      
    - name: Docker login
      run : echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
    
    - name: Build the Docker image with an artifact inside
      run : docker build . --file Dockerfile --tag dr1ff/nintendosdbot:${GITHUB_RUN_ID}
      
    - name: Publish the Docker image
      run : docker push dr1ff/nintendosdbot:${GITHUB_RUN_ID}
      
    
    
    
    
    
